import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React, {useMemo, useState } from "react";


import DropDownInvitationType from '../components/DropdownInvitationType'
import MenuChoice from '../components/MenuChoice'
import firebase from 'firebase/app'
import 'firebase/firestore'
import 'firebase/database'
import FirebaseClient from "../firebaseClient";
import { useNotification } from "../notifications/NotificationContext";
import CagnotteParticipate from '../components/ParticiperCagnotteButton'



export default function Home() {
  FirebaseClient()
  const dispatch = useNotification()


  const [Name, setName] = useState("")
  const [Email, setEmail] = useState("")
  const [brunch, setBrunch]= useState(false)
  const [commentaires, setCommentaire] = useState("")
  const [isLoading , setIsLoading]  = useState(false);
  const [menuChoice, setMenuChoice] = useState("")
  
  const [usecuisinePreferences, setcuisinePreferences] = useState([{name: "Vin d'honneur + cérémonie", isActive: false}, {name: "Vin d'honneur + cérémonie + soirée", isActive: false}, {name: "Je ne serais pas présent", isActive: false}])


  const handleValidation = async (event) => {
    event.preventDefault()
    setIsLoading(true)
    
    return fetch('/api/submit', {
      method: 'POST',
      headers: { 'Accept': 'application/json', 'Content-Type': 'application/json'},
      body: JSON.stringify({
          "nom": Name,
          "email": Email,
          "brunch": brunch,
          "commentaires":commentaires
      })
    }).then((_success) => {
      setIsLoading(false)
            dispatch({
        payload : {
            type: "SUCCESS",
            title: "Participation",
            message:"Votre participation a été enregistré"
        }
    })
    }).catch((err) => {
            setIsLoading(false)
            dispatch({
          payload : {
              type: "ERROR",
              title: "Participation",
              message:"Une erreur s'est produite lors de l'enregistremet de votre participation. Veuillez reessayer." + " " + err.message
          }
      })
    });
    
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Mariage des chouchous</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <div className="flex flex-col items-center justify-center p-4">
          <div className="flex flex-col  items-center">
            <div className="flex flex-row">
              <img className="flex object-cover h-20 w-20" src="assets/1.png" />
              <div className="flex font-theos text-6xl">Cornaline et Prince</div>
              <img className="flex object-cover h-20 w-20" src="assets/2.png" />
            </div>
            <div className="font-dancing">- 29 Octobre 2022 -</div>
          </div>


          <div className="text-5xl font-dancing my-10">Les chouchous se marient !!</div>

          <div className="h-80 w-full">
            <div className="grid grid-cols-4 gap-4">
              <img className="flex object-cover h-80 w-full" src="assets/unnamed-7.jpg"/>
              <img className="flex object-cover h-80 w-full" src="assets/P1377140.jpg"/>
              <img className="flex object-cover h-80 w-full" src="assets/unnamed-6.jpg"/>
              <img className="flex object-cover h-80 w-full" src="assets/unnamed-5.jpg"/>
            </div>
          </div>
          <div className="p-14 text-lg">
            C'est peu après la nouvelle annnée 2018 que Prince et Cornaline se sont rencontrés virtuellement. Au bout d'un mois, Cornaline a réussi à convaincre Prince de faire confiance dans le PFH * et de la rencontrer. Ils se sont vus pour la première fois dans les alentours de la gare de Montparnasse à Paris. Il faut croire que malgré la timidité de chacun, cette rencontre était la bonne, car c'est ce 10 février 2018 que les "chouchous" se sont "adoptés" et ont démarré leur histoire d'amour. 
            A la fois similaires et complémentaires, ils ont su attendrir leur carapace mutuelle et sont vite devenus quasi inséparables, voguant de projets en projet (avec un taux de réalisation aussi développé qu'une paquerette ...) ! Est arrivé par un mois de mars 2020 ensoleilé une sombre affaire de covid, et Cornaline et Prince ont réussi l'exploit de sortir du confinement plus soudés encore. Pour célébrer leur amour, ils ont souhaité se PACSer, malheureusemennt l'administration congolaise n'était pas de leur côté (encore un projet rondement mené jusqu'à sonn terme !). En début 2022, est venu ce projet fou de se marier puis de partir en année sabbatique de noces. Cornaline et Prince sommes heureux de partager avec vous leur projet et espèrent vous compter présent lors du Samedi 29 Octobre 2022 !
          </div>
          <div className="flex flex-col w-full px-14">
            <p className="font-helvetica italic">*Putain de Facteur Humain</p>
          </div>


          <div className="flex flex-col justify-center items-center mt-20">
          <img className="flex object-cover h-20 w-20" src="assets/1.png" />
          <div className="text-5xl font-dancing">Le mariage</div>
          <div className="p-14 text-lg">
            Nous vous invitons à venir célèbrer notre union avec nous et tous les membres, parents et proches de la famille.
            Durant ce jour heureux, nous commencerons par célèbrer notre amour lors d'une cérémonie laique au Prieuré de Vernelle, puis un vin d'honneur sera servi de 17h30 à 18h30, suivit ensuite d'un repas et de la fiesta.
            Retrouvez toutes les informations importantes concernant le lieu et le déroulement de la journée ci-dessous.
          </div>
          </div>
          <div className="text-2xl font-dancing">- 29 Octobre 2022 -</div>
          
          <div className="h-80 w-full py-4">
            <div className="grid grid-cols-4 gap-4">
              <div className="flex flex-col items-center justify-center">
                <div className="flex relative h-80 w-full">
                  <img className="flex object-cover h-80 w-full" src="assets/DJI_0021.MP4.00_05_35_13.Image-fixe008-2-1.jpg"/>
                  <div className="absolute h-32 bg-white bottom-0 w-full opacity-70">
                    <div>Lieu du mariage: Le Prieuré de Vernelle</div>
                    <div className="text-sm">Adresse: Rte d'Evry, 77166</div>
                    <div className="text-sm">Accueil : 15h</div>
                    <div className="text-sm">Cérémonie laique : 15h15</div>
                    <div className="text-sm">Vin d'honneur : 17h30 - 19h30</div>
                    <div className="text-sm">Repas : 19h45</div>
                  </div>
                </div>
              </div>
              <div className="flex flex-col items-center justify-center">
                <div className="flex relative h-80 w-full">
                  <img className="flex object-cover h-80 w-full" src="https://www.transbus.org/dossiers/navettes-autonomes-navly.jpg"/>
                  <div className="absolute h-32 bg-white bottom-0 w-full opacity-70">
                    <div>Navette</div>
                    <div className="text-sm">Une navette sera disponible de minuit à 5h du matin pour relier le Prieuré à l'hôtel Kyriad Brie-Comte-Robert. Ne prenez le volant que si un Sam 0% alcool a été identifié en début de journée (NB: Les controles routiers sont très actifs autour de Suisnes).</div>
                  </div>
                </div>
              </div>
              <div className="flex flex-col items-center justify-center">
                <div className="flex relative h-80 w-full">
                  <img className="flex object-cover h-80 w-full" src="http://www.vernelle.fr/wp-content/uploads/2017/11/20171109_162725.jpg"/>
                  <div className="absolute h-32 bg-white bottom-0 w-full opacity-70">
                    <div>Logements</div>
                    <div className="text-sm">Des logements sont disponiblees sur place et à l'hôtel Kyriad Brie-Comte-Robert. Merci de cocher  la case correspondante dans le formulaire de présence et nous nous chargeons de revenir vers vous avec la repartition des lieux et la négociation du prix de la chambre d'hôtel Kyriad.</div>
                  </div>
                </div>
              </div>
              <div className="flex flex-col items-center justify-center">
                <div className="flex relative h-80 w-full">
                  <img className="flex object-cover h-80 w-full" src="http://www.vernelle.fr/wp-content/uploads/2016/01/octobre-12-739.jpg"/>
                  <div className="absolute h-32 bg-white bottom-0 w-full opacity-70">
                    <div>Rebelote le brunch</div>
                    <div className="text-sm">Dimanche 30 Octobre, un brunch se déroulera au Prieuré de Vernelle à partir de 10h30 jusqu'à 16.</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          


          <img className="flex object-cover h-20 w-20 mt-10" src="assets/1.png" />
          <div className="text-5xl font-dancing">Cagnotte</div>
          <div className="p-14 text-lg">
            Nous avons le projet de partir en sabbatique durant l'année 2023 sur le continent africain. Nous ciblons le pays de natale de Prince pour une première étape, ensuite nous souhaitonns découvrir les savanes sauvages de Tanzanie, ainsi que le désert de Kalahari en passant par les chutes Victoria en Zambie. 
          </div>
          <div className="flex flex-col space-y-5 items-center justify-center">
          <div className="h-80 w-full">
            <div className="grid grid-cols-4 gap-4">
              <div className="flex flex-col items-center justify-center">
                <img className="flex object-cover h-80 w-full" src="assets/Afrique-Namibie-Kalahari-1-2018.jpeg"/>
                <div>Désert du Kalahari - Botswana</div>
              </div>
              <div className="flex flex-col items-center justify-center">
                <img className="flex object-cover h-80 w-full" src="assets/Tanzanie-G719134315.jpeg"/>
                <div>Savane - Tanzanie</div>
              </div>
              <div className="flex flex-col items-center justify-center">
              <img className="flex object-cover h-80 w-full" src="assets/victoria_falls_in_zambie.jpeg"/>
              <div>Chutes Victoria - Zambie</div>
              </div>
              <div className="flex flex-col items-center justify-center">
              <img className="flex object-cover h-80 w-full" src="assets/western-lowland-gorilla-in-forest-odzala-np-republic-of-congo-will-burrard-lucas--natureplcom.jpeg"/>
              <div>Parc national d'Odzala-Kokoua - Congo</div>
              </div>
            </div>
          </div>
          <div className="flex mt-12">
            <CagnotteParticipate/>
          </div>
          </div>
          <div className="w-full flex flex-col py-20  items-center">
          <div className="flex flex-col py-6">
            <img className="flex object-cover h-32" src="assets/rsvp.gif" />
          </div>
          <div className="flex w-full max-w-md mx-auto py-4 items-center justify-center text-sm">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</div>
            
            <form className="flex flex-col py-4  bg-white rounded px-30 justify-center items-center">
              <div className="flex flex-row space-x-4 w-full max-w-md mx-auto">
                <div className="mb-4">
                  <label className="block text-gray-700 text-sm font-bold mb-2" htmlFor="username">
                    Votre Nom et Prénom *
                  </label>
                  <input onChange={((e) => setName(e.target.value))} className="w-full py-3 pl-3 pr-10 text-left bg-white rounded-lg shadow-md cursor-default focus:outline-none focus-visible:ring-2 focus-visible:ring-opacity-75 focus-visible:ring-white focus-visible:ring-offset-orange-300 focus-visible:ring-offset-2 focus-visible:border-indigo-500 sm:text-sm" id="username" type="text" placeholder="Votre nom" />
                  <p className="text-red-500 text-xs italic">Please fill out this field.</p>
                </div>
                <div className="mb-4">
                  <label className="block text-gray-700 text-sm font-bold mb-2" htmlFor="username">
                    Votre email *
                  </label>
                  <input onChange={((e) => setEmail(e.target.value))} className="w-full py-3 pl-3 pr-10 text-left bg-white rounded-lg shadow-md cursor-default focus:outline-none focus-visible:ring-2 focus-visible:ring-opacity-75 focus-visible:ring-white focus-visible:ring-offset-orange-300 focus-visible:ring-offset-2 focus-visible:border-indigo-500 sm:text-sm" id="username" type="text" placeholder="Votre prénom" />
                  <p className="text-red-500 text-xs italic">Please fill out this field.</p>
                </div>
              </div>

              <DropDownInvitationType usecuisinePreferences={usecuisinePreferences} setcuisinePreferences={setcuisinePreferences}></DropDownInvitationType>
              <MenuChoice></MenuChoice>
              

              <div className="flex">
                  <input onChange={((e) => setBrunch(e.target.value))} className="inline-block appearance-none h-5 w-5 border rounded-full border-green-300  bg-white checked:bg-green-400 checked:border-green-300 focus:outline-none transition duration-200 mt-1 align-top bg-no-repeat bg-center bg-contain float-left mr-2 cursor-pointer" type="checkbox" id="inlineCheckbox1"/>
                  <label className="inline-block text-gray-800" htmlFor="inlineCheckbox1">Sera présent au brunch</label>
              </div>

              <div className="flex">
                  <input onChange={((e) => setBrunch(e.target.value))} className="inline-block appearance-none h-5 w-5 border rounded-full border-green-300  bg-white checked:bg-green-400 checked:border-green-300 focus:outline-none transition duration-200 mt-1 align-top bg-no-repeat bg-center bg-contain float-left mr-2 cursor-pointer" type="checkbox" id="inlineCheckbox1"/>
                  <label className="inline-block text-gray-800" htmlFor="inlineCheckbox1">Avez-vous besoin d'un logement?</label>
              </div>


              <div className="flex w-full  py-10 ">
                <textarea onChange={((e) => setCommentaire(e.target.value))} rows="5" type="text" placeholder="commentaires éventuels (intolérances, allergies etc ....)" className="w-full max-w-md mx-auto py pl-3 pr-10 text-left bg-white rounded-lg shadow-md cursor-default focus:outline-none focus-visible:ring-2 focus-visible:ring-opacity-75 focus-visible:ring-white focus-visible:ring-offset-orange-300 focus-visible:ring-offset-2 focus-visible:border-indigo-500 sm:text-sm"/>
              </div>

              <div>
                <div className="flex w-full max-w-md mx-auto  items-center justify-center text-sm">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</div>
              </div>

              <div className="flex py-6">
                <button onClick={handleValidation} disabled={!Name.length || !Email.length} type="submit" className="flex w-96 bg-black hover:bg-gray-700  text-gray-800 font-bold py-3 px-4 rounded-xl justify-center items-center disabled:opacity-40">
                      {
                            isLoading ? <svg className="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                            </svg> : null
                      }
                  <div className="font-montserrat text-sm text-white">Envoyer</div>
                </button>
              </div>
            </form>
          </div>
          <div>

          </div>
        </div>
      </main>
    </div>
  )
}
